### ISSUE TITLE
Request: Rogue CR profiles.

### ISSUE THREAD

**Issue by qwff** [MrTheSoulz/Probably_MrTheSoulz#11]
Would you be open to creating CR profiles for the rogue class? I would be willing to donate some money your way.

**Comment by MrTheSoulz** [comment]
I do have plans for one, will add it officialy to the list.
Any suggestion to what spec i should start with?

**Comment by qwff** [comment]
Great news! Probably start with the Combat spec since it is the most optimal until ilvl 680 followed by Subtlety.

**Comment by MrTheSoulz** [comment]
Ok will finish cleaning up and working on bugs then will start one.

**Comment by MrTheSoulz** [comment]
Ive commited a sub one, more will come later.
Closing this.
