### ISSUE TITLE
Unholy DK Necro-blight Rotation

### ISSUE THREAD

**Issue by qqmore123** [MrTheSoulz/Probably_MrTheSoulz#14]
First of all, Thank you so much for the MTS bundle!
The effort and awesomeness in there really are worth a lot of gratitude :)

My post is related to the UH DK profile. Is it possible for you to implement additional conditions in the rotation to allow a player to use Plague-bringer and Necrotic Plague talents? This spec is preferential for several bosses in BRF and the modifications are not that many.

Also, it may be a good idea to add the pet's interrupt "Leap" to the rotation as well as "Death's Advance" to the codlins which most DKs pick at the moment.

Once again many thanks for your time and effort.

//QQmore

**Comment by MrTheSoulz** [comment]
Thanks for the feedback, will look at this :)

**Comment by qqmore123** [comment]
Also an off topic note, I noticed on Kormog @ BRF the PE stops working while captured in the hands. Is it something wrong in my setup or this is a bug?

**Comment by MrTheSoulz** [comment]
Probably a LOS issue on PE, i have not done any new raids due to being time limited.
I have it on the calendar for this weekend among other things.

**Comment by qqmore123** [comment]
I made the following attempts based on the recently published PE documentation, but they don't quite work. If you can guide me a little I can modify the UH profile to implement use of Necrotic Plague and add in some minor tweaks based on my testing.

1) We need to blow CDs when target is in range not when we are in combat to maximise the benefit.
    For example:
		{ "Death's Advance", { -- Death's Advance
			"modifier.cooldowns",
			"player.spell(Plague Strike).range",
		}},

2) If Necrotic Plague talent is used, refreshing diseases should go something like this:
{ "77575", { --Outbreak
    "target.debuff(55095).duration < 2",
    "!player.spell(Necrotic Plague).exists", --Otherwise outbreak will always be cast looking for Icy Touch
}},
{ "77575", { --Outbreak
    "target.debuff(55078).duration < 2",
    "!player.spell(Necrotic Plague).exists", --Otherwise outbreak will always be cast looking for Blood Pl.
}},
{ "77575", { --Outbreak
    "target.debuff(155159).duration < 2", ---Debuff Necrotic Plague
    "player.spell(Necrotic Plague).exists", --Only when talent is learnt
    "!player.spell(Plague Strike).range", --Maybe use outbreak to refresh only is PS is not in range?
}},
{ "45462", { -- Plague Strike
    {"target.debuff(55095).duration <= 9", "target" },
    "!player.spell(Necrotic Plague).exists", --Only when talent is NOT learnt
    "player.spell(Plague Strike).range", --Use PS if it is in range?
}},

I have an error some where, so when I make these modifications in the Unholy.lua file, I cannot select the MTS Rotation from PE in game. As soon as i disable the modifications, all is back to normal. So yes, I would love to help with what little LUA skills i have. I know DKs very well and I truly believe If you put me on the right track I can make some contributions :).

Looking forward to hearing from you soon.
//QQmore

**Comment by MrTheSoulz** [comment]
1) This Everything inside this nest will only be casted IF target is in 6 yards of player and cooldowns tooggle is enabled.
You should always try to nest stuff whenever possivel, adding the same condition over and over instead of nesting means
everytime PE cycles it wastes resorces instead of just checking it once and then if it can cast whatever is inside it.
{{ -- Cooldown's
    1.1) Example:
    { "96268" },-- Deaths Advance // Cast this whenever the nest us true and available.
    { "Another spell", "condicion thats not on nest", "target" },
    { "Another spell", {
        "condicion 1",
        "condition 2"
    }, "target" }
},{ "target.range < 6", "modifier.cooldowns" }},

2) You had a error on line 29
{ "77575", { --Outbreak
    "target.debuff(55095).duration < 2",
    "!player.spell(Necrotic Plague).exists" --Otherwise outbreak will always be cast looking for Icy Touch
}, "target" },
{ "77575", { --Outbreak
    "target.debuff(55078).duration < 2",
    "!player.spell(Necrotic Plague).exists" --Otherwise outbreak will always be cast looking for Blood Pl.
}, "target" },
{ "77575", { --Outbreak
    "target.debuff(155159).duration < 2", ---Debuff Necrotic Plague
    "player.spell(Necrotic Plague).exists", --Only when talent is learnt
    "!player.spell(Plague Strike).range" --Maybe use outbreak to refresh only is PS is not in range?
}, "target" },
{ "45462", { -- Plague Strike
    "target.debuff(55095).duration <= 9",
    "!player.spell(Necrotic Plague).exists", --Only when talent is NOT learnt
    "player.spell(Plague Strike).range" --Use PS if it is in range?
}, "target" },

Also good formating is important to keep the project clean and easy to read.

**Comment by MrTheSoulz** [comment]
Also the correct way to do this:
"!player.spell(Necrotic Plague).exists", --Only when talent is NOT learnt

is:
"!talent(7, 1)", --Only when talent is NOT learnt

Row 7 talent 1

**Comment by qqmore123** [comment]
Thank you very much for your prompt reply. I used the tips you gave me to implement using Necrotic Plague. I am attaching here a copy of the blue file incase i made any mistakes, but i have tested it and it seems to work fine now. Made some minor changes to Festering Strike in the AoE rotation to get rid of frost runes quicker as well.

Here it is:

local fetch = ProbablyEngine.interface.fetchKey
function exeOnLoad()



end

local inCombat = {

	

	-- Buffs
		{ "48263", { -- Blood
			"player.seal != 1", 
			(function() return fetch("mtsconfDkUnholy", "Presence") == 'Blood' end),
		}, nil }, 
		{ "48266", { -- Frost
			"player.seal != 2", 
			(function() return fetch("mtsconfDkUnholy", "Presence") == 'Frost' end),
		}, nil },
		{ "48265", { -- Unholy
			"player.seal != 3", 
			(function() return fetch("mtsconfDkUnholy", "Presence") == 'Unholy' end),
		}, nil },
		{ "57330", "!player.buffs.attackpower" }, -- Horn of Winter

	-- Keybinds 
		{ "42650", "modifier.control" }, -- Army of the Dead
		{ "51052", "modifier.alt" }, -- AMZ
		{ "152280", "modifier.shift", "target.ground" }, -- Defile
		{ "43265", "modifier.shift", "target.ground" }, -- Death and Decay
	
	-- Pet
		{ "46584", "!pet.exists" }, -- Raise Dead
		{ "63560" }, -- Dark Transformation

	-- Interrupts 
		{ "47528", { -- Mind freeze
			"target.interruptsAt(50)", 
			"modifier.interrupts" 
		}, "target" }, 
		{ "47476", { -- Strangulate
			"target.interruptsAt(50)", 
			"modifier.interrupts", 
			"!player.modifier.last(47528)"
		}, "target" }, 
		{ "108194", { -- Asphyxiate
			"target.interruptsAt(50)", 
			"!modifier.last(47528)" 
		}, "target" }, 
		{ "47482", { -- Leap
			"modifier.interrupts" 
		}, "target" }, 

	-- Def cooldowns // heals
		{ "#5512", "player.health < 85"},--Healthstone
		{ "48792", (function() return mts.dynamicEval("player.health <= " .. fetch('mtsconfDkUnholy', 'IceboundFortitude')) end) }, -- Icebound Fortitude
		{ "48743", (function() return mts.dynamicEval("player.health <= " .. fetch('mtsconfDkUnholy', 'DeathPact')) end) }, -- Death Pact
		{ "108196", (function() return mts.dynamicEval("player.health <= " .. fetch('mtsconfDkUnholy', 'DeathSiphon')) end) },-- Death Siphon
		{ "49039", { -- Lichborne //fear 
			"player.state.fear", 
			"player.runicpower >= 40", 
			"player.spell.exists(49039)" 
		}},
		{ "49039", { -- Lichborne //sleep 
			"player.state.sleep", 
			"player.runicpower >= 40", 
			"player.spell.exists(49039)" 
		}}, 
		{ "49039", { -- Lichborne //charm 
			"player.state.charm", 
			"player.runicpower >= 40", 
			"player.spell.exists(49039)" 
		}},
		{ "49998", { -- Death Strike With Dark Succor
			"player.buff(10156", 
			(function() return mts.dynamicEval("player.health <= " .. fetch('mtsconfDkUnholy', 'DeathStrikeDS')) end)
		}}, 
	
	-- Cooldowns
		 { "Empower Rune Weapon", {
			"modifier.cooldowns", 
			"player.runicpower <= 70", 
			"player.runes(blood).count = 0", 
			"player.runes(unholy).count = 0", 
			"player.runes(frost).count = 0", 
			"player.runes(death).count = 0",
			(function() return fetch("mtsconfDkUnholy", "ERP") == 'Allways' end)
		}},
		{ "96268", { -- Death's Advance
			"modifier.cooldowns",
		}},
		{ "Summon Gargoyle", {
			"modifier.cooldowns",
			(function() return fetch("mtsconfDkUnholy", "SG") == 'Allways' end)
		} },
		{ "115989", { -- Unholy Blight
			"!talent(7, 1)",
			"modifier.cooldowns",
			"target.debuff(55095)",
			(function() return fetch("mtsconfDkUnholy", "UB") == 'Allways' end) --was "SG"
		}}, 
		{ "115989", { -- Unholy Blight
			"!talent(7, 1)",
			"modifier.cooldowns",
			"target.debuff(55078)",
			(function() return fetch("mtsconfDkUnholy", "UB") == 'Allways' end)
		}},
		{ "115989", { -- Unholy Blight -- For NP
			"talent(7, 1)",
			"modifier.cooldowns",
			"target.debuff(155159)",
			(function() return fetch("mtsconfDkUnholy", "UB") == 'Allways' end)
		}}, 
		{ "20572", { -- Blood Fury
			"modifier.cooldowns",
			(function() return fetch("mtsconfDkUnholy", "BF") == 'Allways' end)
		} },
	
	-- Cooldowns boss
		{ "Empower Rune Weapon", {
			"modifier.cooldowns", 
			"player.runicpower <= 70", 
			"player.runes(blood).count = 0", 
			"player.runes(unholy).count = 0", 
			"player.runes(frost).count = 0", 
			"player.runes(death).count = 0",
			"target.boss",
			(function() return fetch("mtsconfDkUnholy", "ERP") == 'Boss' end)
		}},
		{ "96268", { -- Death's Advance
			"modifier.cooldowns",
			"target.boss",
		}},
		{ "#118882", { -- Scabbrad of Kyanos
			"modifier.cooldowns",
			"target.boss",
		}},
		{ "Summon Gargoyle", {
			"modifier.cooldowns",
			"target.boss",
			(function() return fetch("mtsconfDkUnholy", "SG") == 'Boss' end)
		} },
		{ "115989", { -- Unholy Blight
			"!talent(7, 1)",
			"modifier.cooldowns",
			"target.debuff(55095)",
			"target.boss",
			(function() return fetch("mtsconfDkUnholy", "UB") == 'Boss' end)
		}}, 
		{ "115989", { -- Unholy Blight
			"!talent(7, 1)",
			"modifier.cooldowns",
			"target.debuff(55078)",
			"target.boss",
			(function() return fetch("mtsconfDkUnholy", "UB") == 'Boss' end)
		}}, 
		{ "115989", { -- Unholy Blight -- For NP
			"talent(7, 1)",
			"modifier.cooldowns",
			"target.debuff(155159)",
			"target.boss",
			(function() return fetch("mtsconfDkUnholy", "UB") == 'Allways' end)
		}}, 
		{ "20572", { -- Blood Fury
			"modifier.cooldowns",
			"target.boss",
			(function() return fetch("mtsconfDkUnholy", "BF") == 'Boss' end)
		} }, 

	-- Spell Steal
		{ "77606", "@mtsLib.DarkSimUnit('target')", "target" }, -- Dark Simulacrum
		{ "77606", "@mtsLib.DarkSimUnit('focus')", "focus" },  -- Dark Simulacrum
	
	-- Plague Leech
		{ "123693", {
			"!talent(7, 1)",
			"target.debuff(55095)",-- Target With Frost Fever
			"target.debuff(55078)",-- Target With Blood Plague
			"player.runes(unholy).count = 0",-- With 0 Unholy Runes
			"player.runes(frost).count = 0",-- With 0 Frost Runes
			"player.runes(death).count = 0",-- With 0 Death Runes
			"!modifier.last"
		}},
		{ "123693", {
			"talent(7, 1)",
			"target.debuff(155159)",-- Target With NP
			"player.runes(unholy).count = 0",-- With 0 Unholy Runes
			"player.runes(frost).count = 0",-- With 0 Frost Runes
			"player.runes(death).count = 0",-- With 0 Death Runes
			"!modifier.last"
		}},  

	-- Proc
		{ "47541", "player.buff(Sudden Doom)", "target"  }, -- Death Coil w/t Sudden Doom

	-- Soul Reaper
		{ "Soul Reaper", { "!target.debuff", "target.health < 45" }, "target" },

	-- Excess RP
		{ "47541", "player.runicpower >= 75", "target"  }, -- Death Coil

	-- Diseases
		{ "77575", { --Outbreak
			"target.debuff(55095).duration < 2",
			"!talent(7, 1)",
		}, "target" },
		{ "77575", { --Outbreak 
			"target.debuff(55078).duration < 2",
			"!talent(7, 1)",
		}, "target" },
		{ "77575", { --Outbreak for NP
			"target.debuff(155159).duration < 2",
			"talent(7, 1)",
		}, "target" },
		{ "45462", { -- Plague Strike
			"target.debuff(55095).duration <= 9",
			"!talent(7, 1)", 
		}, "target" },
		{ "45462", { -- Plague Strike
			"target.debuff(55078).duration <= 9",
			"!talent(7, 1)", 
		}, "target" },
		{ "45462", { -- Plague Strike
			"target.debuff(155159).duration <= 9",
			"talent(7, 1)", 
		}, "target" },


	{{-- AoE // Smart
		{ "43265", "target.range < 7", "target.ground" }, -- Death and Decay
		{ "152280", "target.range < 7", "target.ground" }, -- Defile
		{ "50842", { -- Blood Boil // death
			"player.runes(death).count >= 1",
			"target.range <= 10"
		}, nil },
		{ "50842", { -- Blood Boil // blood
			"!talent(7, 1)",
			"player.runes(blood).count >= 1",
			"target.debuff(55095).duration < 3", 
			"target.debuff(55078).duration <3",
			"target.range <= 10" 
		}},
		{ "50842", {  -- Blood Boil // death
			"!talent(7, 1)",
			"player.runes(death).count >= 1",
			"target.debuff(55095).duration < 3", 
			"target.debuff(55078).duration <3",
			"target.range <= 10" 
		}},
		{ "50842", { -- Blood Boil // blood // NP
			"talent(7, 1)",
			"player.runes(blood).count >= 1",
			"target.debuff(155159).duration < 3", 
			"target.range <= 10" 
		}},
		{ "50842", {  -- Blood Boil // death // NP
			"talent(7, 1)",
			"player.runes(death).count >= 1",
			"target.debuff(155159).duration < 3", 
			"target.range <= 10" 
		}},
		{ "Festering Strike", { "player.runes(blood) = 2", "player.runes(frost) = 2" }, "target"  }, --Testing
		{ "85948" }, -- Festering Strike
		{ "47541", "player.runicpower >= 40", "target"  }, -- Death Coil
	}, { (function() return fetch('mtsconf','SAoE') end), "player.area(10).enemies >= 4" }},

	{{-- AoE

		{ "43265", "target.range < 7", "target.ground" }, -- Death and Decay
		{ "152280", "target.range < 7", "target.ground" }, -- Defile
		{ "50842", { -- Blood Boil // death
			"player.runes(death).count >= 1",
			"target.range <= 10"
		}, nil },
		{ "50842", { -- Blood Boil // blood
			"!talent(7, 1)",
			"player.runes(blood).count >= 1",
			"target.debuff(55095).duration < 3", 
			"target.debuff(55078).duration <3",
			"target.range <= 10" 
		}},
		{ "50842", {  -- Blood Boil // death
			"!talent(7, 1)",
			"player.runes(death).count >= 1",
			"target.debuff(55095).duration < 3", 
			"target.debuff(55078).duration <3",
			"target.range <= 10" 
		}},
		{ "50842", { -- Blood Boil // blood // NP
			"talent(7, 1)",
			"player.runes(blood).count >= 1",
			"target.debuff(155159).duration < 3", 
			"target.range <= 10" 
		}},
		{ "50842", {  -- Blood Boil // death // NP
			"talent(7, 1)",
			"player.runes(death).count >= 1",
			"target.debuff(155159).duration < 3", 
			"target.range <= 10" 
		}},
		{ "Festering Strike", { "player.runes(blood) = 2", "player.runes(frost) = 2" }, "target"  }, --Testing
		{ "85948" }, -- Festering Strike
	}, "modifier.multitarget"},

	-- Rotation
		{ "55090", "player.runes(unholy) = 2", "target"  }, -- Scourge Strike
		{ "43265", { -- Death and Decay
			"target.range < 7",
			(function() return fetch("mtsconfDkUnholy", "DnD") == 'Allways' end)
		}, "target.ground" }, 
		{ "152280", {
			"target.range < 7",
			(function() return fetch("mtsconfDkUnholy", "Defile") == 'Allways' end)
		}, "target.ground" }, -- Defile
		{ "Fastering Strike", { "player.runes(unholy) = 2", "player.runes(blood) = 2" }, "target"  },
		{ "55090" },-- Scourge Strike
		{ "Festering Strike" },
		{ "47541" }, -- Death Coil

	-- Blood Tap
		{{
			{ "45529", "player.runes(unholy).count = 0" }, --Blood Tap
			{ "45529", "player.runes(frost).count = 0" }, -- Blood Tap
			{ "45529", "player.runes(blood).count = 0" }, -- Blood Tap
		} , {
			"player.buff(Blood Charge).count >= 5",
			"player.runes(death).count = 0",
			"!lastcast(45529)"
		}},

}

local outCombat = {
  
	{ "46584", "!pet.exists" }, -- Raise Dead

	-- Buffs
		{ "48263", { -- Blood
			"player.seal != 1", 
			(function() return fetch("mtsconfDkUnholy", "Presence") == 'Blood' end),
		}, nil }, 
		{ "48266", { -- Frost
			"player.seal != 2", 
			(function() return fetch("mtsconfDkUnholy", "Presence") == 'Frost' end),
		}, nil },
		{ "48265", { -- Unholy
			"player.seal != 3", 
			(function() return fetch("mtsconfDkUnholy", "Presence") == 'Unholy' end),
		}, nil },
		{ "57330", { -- Horn of Winter
			"!player.buffs.attackpower",
			(function() return fetch('mtsconfDkUnholy','HornOCC') end)
		}}, 

}

ProbablyEngine.rotation.register_custom(
	252, mts.Icon..
	"|r[|cff9482C9MTS|r][\124cffC41F3BDeathKnight-Unholy|r]", 
	inCombat, 
	outCombat, 
	exeOnLoad)

**Comment by MrTheSoulz** [comment]
Will review this soon, thanks for the help :)

**Comment by MrTheSoulz** [comment]
Okay, ive review & commited this.
I also cleaned up the CR a lil bit, it should perform better now.

I havent test it will do so later tonight, would appreciate if you would test it out to confirm i havent broken any of your work :)

Thanks!

**Comment by qqmore123** [comment]
Awesome! Will do some testing and will get back to you asap.
Also I started testing Destro lock, more to come tomorrow :)

**Comment by MrTheSoulz** [comment]
Sorry not a mac user but you could do like me (i do it on linux) and run WoW on WINE and then run FireHack.

**Comment by qqmore123** [comment]
After some testing using FireHack, the SAoE is not working at all for me i'm afraid. In the tool tip it says that SAoE is "able" but as a DK it did not cast any blood boils. Am I doing something wrong?

Also, I think it maybe a good idea to add this to the AoE and SAoE rotation:
	{ "108199", "player" }, --Gorefiend's Grasp

What do you think?

Best Regards,
QQmore

**Comment by MrTheSoulz** [comment]
Will review SAoE and look into the request.
Thanks for the feedback! :D

**Comment by MrTheSoulz** [comment]
i cant implement Gorefiend's Grasp beacuse of obious reasons, SAoE should be fixed in the next release.
Closing this.
