### ISSUE TITLE
Review Clarity of Will (Priest Disc)

### ISSUE THREAD

**Issue by MrTheSoulz** [MrTheSoulz/Probably_MrTheSoulz#15]
In request of "yobleed" from OC.

Details:
http://www.wowhead.com/spell=152118/clarity-of-will

**Comment by SvsGit** [comment]
-- Clarity of Will
 { "152118", { 
 	  "!tank.buff(152118).any",
	  "tank.health <= 100"
	}, "tank" },

**Comment by MrTheSoulz** [comment]
Should now be fixed
