### ISSUE TITLE
Shaman Error

### ISSUE THREAD

**Issue by mspencer92** [MrTheSoulz/Probably_MrTheSoulz#20]
I am getting this error 218x ...ddOns\Probably_MrTheSoulz\rotations\shaman\resto.lua:27: attempt to call global 'unit' (a nil value)

I am also getting 266x Probably\system\core\parser.lua:213: attempt to index local 'arguments' (a function value)  once I fix the above error or atleast think I fixed it.

**Comment by skat2006** [comment]
This can be used like temporary solution - https://github.com/MrTheSoulz/Probably_MrTheSoulz/pull/21

**Comment by MrTheSoulz** [comment]
Closing this, skat2006 commited a fix.
Thanks.
