### ISSUE TITLE
Disc priest

### ISSUE THREAD

**Issue by verysimplenick** [MrTheSoulz/Probably_MrTheSoulz#8]
Hi, I want use your scripts, but need some help with swd in draenor. I want interrupt cc from poly, fear, maybe freezing trap by Holy fire with glyph. How I can create script for probably?

**Comment by MrTheSoulz** [comment]
Sorry trying to understand the question, you would like to break a CC like poly using SW:D?
Please provide more clear details like a use case.

**Comment by MrTheSoulz** [comment]
Locking this due to a lack of answer.
